version: '3.8'

services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../src:/app/src
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=development
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  test:
    build:
      context: ..
      dockerfile: docker/Dockerfile.test
    volumes:
      - ../src:/app/src
      - ../tests:/app/tests
      - ../test-reports:/app/test-reports:rw
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=test
      - PYTEST_ADDOPTS="--html=/app/test-reports/report.html --self-contained-html --cov=src --cov-report=html:/app/test-reports/coverage"
    depends_on:
      - api
